Elantra = read.csv(choose.files())
ElantraTrain = subset(Elantra, Year <= 2012)
ElantraTest = subset(Elantra, Year > 2012)
ElantraLM = lm(ElantraSales ~ Unemployment + CPI_all + CPI_energy + Queries, data = ElantraTrain)
summary(ElantraLM)
ElantraLM2 = lm(ElantraSales ~ Unemployment + CPI_all + CPI_energy + Queries + Month, data = ElantraTrain)
summary(ElantraLM2)
ElantraTrain$MonthFactor = as.factor(ElantraTrain$Month)
ElantraTest$MonthFactor = as.factor(ElantraTest$Month)
ElantraLM = lm(ElantraSales ~ Unemployment + Queries + CPI_energy + CPI_all + MonthFactor, data=ElantraTrain)
summary(ElantraLM)
cor(ElantraTrain[c("Unemployment","Month","Queries","CPI_energy","CPI_all")])
ElantraLM = lm(ElantraSales ~ Unemployment + CPI_energy + CPI_all + MonthFactor, data=ElantraTrain)
summary(ElantraLM)
PredictTest = predict(ElantraLM, newdata=ElantraTest)
SSE = sum((PredictTest - ElantraTest$ElantraSales)^2)
SSE
mean(ElantraTrain$ElantraSales)
SST = sum((mean(ElantraTrain$ElantraSales) - ElantraTest$ElantraSales)^2)
1 - SSE/SST
max(abs(PredictTest - ElantraTest$ElantraSales))
which.max(abs(PredictTest - ElantraTest$ElantraSales))
